version: "3.9"

services:
  # Data-only container for shared_resources
  shared_resources:
    image: "busybox"
    volumes:
      - gem_cache:/web/rubygems/2.7.2
      - node_modules:/web/app/node_modules

  #
  # Infrastructure Services
  #
  mongodb:
    build: ./site/mongodb
    hostname: mongodb
    restart: always
    environment:
      # - MONGO_INITDB_DATABASE: ea_enterprise
      - MONGO_INITDB_ROOT_USERNAME="root"
      - MONGO_INITDB_ROOT_PASSWORD="example"
    # networks:
    #   - backend
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017

  rabbitmq:
    build: ./site/rabbitmq
    hostname: rabbitmq
    env_file:
      - ./site/rabbitmq/rabbitmq.env
    # networks:
    #   - backend
    volumes:
      - rabbitmq_etc:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq/
      - ./site/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./site/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    build: ./site/redis
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  #
  # Microservices
  #
  enroll:
    build:
      context: ../enroll
      dockerfile: ../ea_enterprise/site/enroll_service/Dockerfile
    volumes_from:
      - shared_resources
    volumes:
      - ../enroll:/enroll
    env_file:
      - ./site/.env
    depends_on:
      - mongodb
      - rabbitmq
      - redis
    links:
      - fdsh_gateway
      - medicaid_gateway
      - polypress
    ports:
      - "3002:3000"
    command: bash -c "rm -f tmp/pids/server.pid && mkdir -p tmp/pids && bundle exec puma -C config/puma.rb"
    # command: bash -c "rm -f tmp/pids/server.pid && mkdir -p tmp/pids && yarn install --check-files && bundle exec rails assets:precompile && bundle exec puma -C config/puma.rb"


  fdsh_gateway:
    build:
      context: ../fdsh_gateway
      dockerfile: ../ea_enterprise/site/fdsh_gateway_service/Dockerfile
    volumes_from:
      - shared_resources
    volumes:
      - ../fdsh_gateway:/fdsh_gateway
    env_file:
      - ./site/.env
    depends_on:
      - mongodb
      - rabbitmq
    command: /fdsh_gateway/bin/rails server --port 3006 --binding 0.0.0.0
    links:
      - polypress
    ports:
      - "3006:3006"

  medicaid_gateway:
    build:
      context: ../medicaid_gateway
      dockerfile: ../ea_enterprise/site/medicaid_gateway_service/Dockerfile
    command: bundle install
    volumes_from:
      - shared_resources
    volumes:
      - ../medicaid_gateway:/medicaid_gateway
    env_file:
      - ./site/.env
      - ./site/medicaid_gateway_service/.env
    depends_on:
      - mongodb
      - rabbitmq
    links:
      - polypress
      - mitc
    ports:
      - "3005:3005"
    command: /medicaid_gateway/bin/rails server --port 3005 --binding 0.0.0.0

  mitc:
    build:
      context: ../medicaid_eligibility
      dockerfile: ../ea_enterprise/site/mitc_service/Dockerfile
    volumes:
      - ../medicaid_eligibility:/mitc
      - type: tmpfs
        target: /mitc/tmp/pids/
    links:
      - polypress
    command: sleep 300
    # command: bin/rails server --port 3001 --binding 0.0.0.0
    ports:
      - "3001:3001"

  polypress:
    build:
      context: ../polypress
      dockerfile: ../ea_enterprise/site/polypress_service/Dockerfile
    command: bundle install
    volumes_from:
      - shared_resources
    volumes:
      - ../polypress:/polypress
    env_file:
      - ./site/.env
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "3003:3003"
    command: sleep 300
    # command: /polypress/bin/rails server --port 3003 --binding 0.0.0.0

volumes:
  gem_cache:
  node_modules:
  mongodb:
  mongodb_config:
  rabbitmq_etc:
  rabbitmq_data:
  rabbitmq_logs:
