version: "3.9"

services:
  #
  # Infrastructure Services
  #
  mongodb:
    image: mongo:4.2
    hostname: mongodb
    #mem_limit: 4000m #uncomment this if you want to replicate mongo memory on prod
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet

  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    env_file:
      - ./site/rabbitmq/rabbitmq.dev.env
    volumes:
      - rabbitmq_etc:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq/
      - ./site/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./site/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity


  redis:
    image: redis:7.0
    ports:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  #
  # Reverse proxy for medicaid_gateway:
  # uncomment this or tweak it to your need to replicate an extreme issue with the load balancer
  #

  # mcgw_nginx:
  #   image: nginx:1.22
  #   volumes:
  #     - ${PWD}/site/mcgw_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     medicaid_gateway:
  #       condition: service_started
  #   links:
  #     - medicaid_gateway
  #   ports:
  #     - 3030:3030

  keycloak:
    # profiles:
    #   - keycloak
    #   - all
    image: quay.io/keycloak/keycloak:23.0.5
    # env_file:
    #   - ./site/keycloak/keycloak.dev.env
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # - KEYCLOAK_IMPORT=/tmp/realm-export.json
    ports:
      - 8080:8080
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      start_period: 20s
      interval: 3m
    command: ["start-dev"]

  enroll_helper:
    build:
      context: ../enroll
      dockerfile: ../ea_enterprise/site/enroll_service/Dockerfile
      args:
        BUNDLER_VERSION_OVERRIDE: '2.2.12'
    image: enroll:dev-0.1.0
    environment:
      - SHELL=/bin/bash
    volumes:
      - ../enroll:/enroll
      - ${PWD}/hotpatches/mongoid-enroll.yml:/enroll/config/mongoid.yml:ro
      - enroll_node_modules_cache:/enroll/node_modules
      - enroll_packs_cache:/enroll/public/packs
      - enroll_assets_cache:/enroll/public/assets
      - enroll_rails_cache:/enroll/tmp/cache
      - ../aca_entities:/aca_entities
    env_file:
      - ./site/.env.dev
      - ./site/rabbitmq/rabbitmq.dev.env
      - env.dev
    depends_on:
      enroll:
        condition: service_healthy
    # links:
    #   - mongodb
    #   - fdsh_gateway
    #   - medicaid_gateway
    #   - polypress
    command: bash -c "bundle install && bin/webpack && bundle exec rake 'seed:translations[db/seedfiles/english_translations_seed.rb]'"

  #
  # Microservices
  #

  enroll:
    build:
      context: ../enroll
      dockerfile: ../ea_enterprise/site/enroll_service/Dockerfile
    image: enroll:dev-0.1.0
    environment:
      - SHELL=/bin/bash
    volumes: 
      - ../enroll:/enroll
      - ${PWD}/hotpatches/cucumber_env.rb:/enroll/features/support/env.rb:ro
      - ${PWD}/hotpatches/mongoid-enroll.yml:/enroll/config/mongoid.yml:ro
      - ${PWD}/hotpatches/mongoid-enroll.yml:/enroll/components/financial_assistance/spec/dummy/config/mongoid.yml:ro
      - ${PWD}/hotpatches/mongoid-enroll.yml:/enroll/components/benefit_markets/spec/dummy/config/mongoid.yml:ro
      - ${PWD}/hotpatches/mongoid-enroll.yml:/enroll/components/notifier/spec/dummy/config/mongoid.yml:ro
      - ${PWD}/hotpatches/mongoid-enroll.yml:/enroll/components/sponsored_benefits/spec/dummy/config/mongoid.yml:ro
      - ${PWD}/hotpatches/mongoid-enroll.yml:/enroll/components/transport_profiles/spec/dummy/config/mongoid.yml:ro
      - ${PWD}/hotpatches/mongoid-enroll.yml:/enroll/components/benefit_sponsors/spec/dummy/config/mongoid.yml:ro
      - enroll_node_modules_cache:/enroll/node_modules
      - enroll_packs_cache:/enroll/public/packs
      - enroll_rails_cache:/enroll/tmp/cache
      - enroll_assets_cache:/enroll/public/assets
      - ../aca_entities:/aca_entities
      - ../event_source:/event_source
      - ${PWD}/hotpatches/keycloack/saml_information.rb:/enroll/config/saml_information.rb:ro
    env_file:
      - ./site/.env.dev
      - ./site/rabbitmq/rabbitmq.dev.env
      - env.dev
      - sso.dev.env
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3002 || exit 1
      start_period: 70s # yes, enroll takes forever to load, tweak it further if you need to
      interval: 3m
    # links:
    #   - mongodb
    #   - fdsh_gateway
    #   - medicaid_gateway
    #   - polypress
    ports:
      - "3002:3002"
    # don't set CLIENT here, change it on env.dev file :)
    command: bash -c "rm -rf tmp/pids/server.pid && mkdir -p tmp/pids && bundle install && bundle exec rake configuration:client_configuration_toggler && bin/rails server --port 3002 --binding 0.0.0.0"


  fdsh_gateway:
    profiles:
      - fdsh_gateway
      - all
    build:
      context: ../fdsh_gateway
      dockerfile: ../ea_enterprise/site/fdsh_gateway_service/Dockerfile
    image: fdsh_gateway:dev-0.1.0
    volumes:
      - ../fdsh_gateway:/fdsh_gateway
      - ${PWD}/hotpatches/mongoid-fdsh.yml:/fdsh_gateway/config/mongoid.yml:ro
      - ../aca_entities:/aca_entities
      - ../event_source:/event_source
    env_file:
      - ./site/.env.dev
      - ./site/rabbitmq/rabbitmq.dev.env
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: bash -c "rm -rf tmp/pids/server.pid && mkdir -p tmp/pids && bin/rails server --port 3006 --binding 0.0.0.0"
    links:
      - mongodb
      - rabbitmq
    ports:
      - "3006:3006"

  medicaid_gateway_helper:
    profiles:
      - medicaid_gateway
      - all
    build:
      context: ../medicaid_gateway
      dockerfile: ../ea_enterprise/site/medicaid_gateway_service/Dockerfile
    image: medicaid_gateway:dev-0.1.0
    volumes:
      - ../medicaid_gateway:/medicaid_gateway
      - mcg_rails_cache:/medicaid_gateway/tmp/cache
      - mcg_bundle:/bundle
      - mcg_node_modules:/medicaid_gateway/node_modules
      - mcg_packs:/medicaid_gateway/public/packs
      - ${PWD}/hotpatches/MG-stimulus.rb:/medicaid_gateway/config/initializers/stimulus_reflex.rb

    env_file:
      - ./site/.env.dev
      - ./site/rabbitmq/rabbitmq.dev.env
      - ./site/medicaid_gateway_service/.env.dev
    depends_on:
      medicaid_gateway:
        condition: service_healthy
    links:
      - mitc
      - mongodb
      - rabbitmq
      - redis
    command: bash -c "bundle exec rake configuration:client_configuration_toggler client='dc' && bin/webpack"


  medicaid_gateway:
    profiles:
      - medicaid_gateway
      - all
    build:
      context: ../medicaid_gateway
      dockerfile: ../ea_enterprise/site/medicaid_gateway_service/Dockerfile
    image: medicaid_gateway:dev-0.1.0
    volumes:
      - ../medicaid_gateway:/medicaid_gateway
      - mcg_rails_cache:/medicaid_gateway/tmp/cache
      - mcg_bundle:/bundle
      - mcg_node_modules:/medicaid_gateway/node_modules
      - mcg_packs:/medicaid_gateway/public/packs
      - ../aca_entities:/aca_entities
      - ${PWD}/hotpatches/MG-stimulus.rb:/medicaid_gateway/config/initializers/stimulus_reflex.rb
    env_file:
      - ./site/.env.dev
      - ./site/rabbitmq/rabbitmq.dev.env
      - ./site/medicaid_gateway_service/.env.dev
      - env.dev
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - mitc
      - mongodb
      - rabbitmq
      - redis
    ports:
      - "3005:3005"
    healthcheck:
      test: curl --fail http://localhost:3005 || exit 1
      start_period: 20s 
      interval: 3m
    command: bash -c "rm -rf tmp/pids/server.pid && mkdir -p tmp/pids && bin/rails server --port 3005 --binding 0.0.0.0"
    
  mitc:
    profiles:
      - medicaid_gateway
      - all
    build:
      context: ../medicaid_eligibility
      dockerfile: ../ea_enterprise/site/mitc_service/Dockerfile
    image: mitc:dev-0.1.0
    volumes:
      - ../medicaid_eligibility:/mitc
      - mitc_gem_cache:/usr/local/bundle/2.3
      - type: tmpfs
        target: /mitc/tmp/pids/
    command: bash -c "bin/rails server --port 3001 --binding 0.0.0.0"
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_healthy
    links:
      - redis

  polypress:
    profiles:
      - polypress
      - all
    build:
      context: ../polypress
      dockerfile: ../ea_enterprise/site/polypress_service/Dockerfile
    image: polypress:dev-0.1.0
    volumes:
      - ../polypress:/polypress
      - polypress_gem_cache:/usr/local/bundle/2.7
    env_file:
      - ./site/.env.dev
      - ./site/rabbitmq/rabbitmq.dev.env
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "3003:3003"
    command: bash -c "rm -rf tmp/pids/server.pid && mkdir -p tmp/pids && bin/rails server --port 3003 --binding 0.0.0.0"
    links:
      - mongodb
      - rabbitmq


volumes:
  mitc:
  fdsh_gem_cache:
  polypress_gem_cache:
  mitc_gem_cache:
  node_modules_cache:
  packs_cache:
  mongodb:
  mongodb_config:
  rabbitmq_etc:
  rabbitmq_data:
  rabbitmq_logs:
  mcg_rails_cache:
  mcg_bundle:
  mcg_node_modules:
  mcg_packs:
  mcg_gem_cache:
  enroll_gem_cache:
  enroll_node_modules_cache:
  enroll_packs_cache:
  enroll_rails_cache:
  enroll_assets_cache:

